### ISSUE TITLE
Missing from Steam Workshop

### ISSUE THREAD

**Issue by chennin** [oskar94/Known-Precursor#14]
Hello! Thank you for this mod!

It seems the mod has gone invisible on Steam. Was this intentional?

![image](https://user-images.githubusercontent.com/2653277/232323312-22cff462-f039-4592-acf0-3fe3460572c9.png)

**Comment by oskar94** [comment]
For some reason the mod has been stuck waiting for automatic content check for over 8 hours now. ![](https://i.imgur.com/9ZScjXt.png)
Have contacted steam support to see if it can be fixed.

**Comment by oskar94** [comment]
Looks like it finally completed and should be back up.
